# This file is generated by the spm_repository rule.

load(
    "@cgrindel_rules_spm//spm:defs.bzl", 
    "spm_package", 
    "spm_swift_library",
    "spm_clang_library",
)

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "all_srcs",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)

PACKAGE_DESCRIPTIONS_JSON = """
{pkg_descs_json}
"""

DEPENDENCIES_JSON = """
{dependencies_json}
"""

spm_package(
    name = "build",
    srcs = [":all_srcs"],
    package_descriptions_json = PACKAGE_DESCRIPTIONS_JSON,
    dependencies_json = DEPENDENCIES_JSON,
    package_path = "external/{spm_repos_name}",
    clang_module_headers = {
{clang_module_headers}
    }
)

