"""Tested/Supported Bazel Versions"""

CURRENT_BAZEL_VERSION = "5.1.1"

OTHER_BAZEL_VERSIONS = [
    "6.0.0-pre.20220405.2",
]

SUPPORTED_BAZEL_VERSIONS = [
    CURRENT_BAZEL_VERSION,
] + OTHER_BAZEL_VERSIONS
