#!/usr/bin/env zsh

# This file exists to support linting in vim using vim-ale.
# This script ensures that the config file is used when linting.

set -euo pipefail

script_dir="${0:A:h}"
config_file="${script_dir}/.swiftlint.yml"

swiftlint --config "${config_file}" "${@}"



