#!/usr/bin/env zsh

# This file exists to support formatting in vim using vim-ale.
# This script ensures that the config file is used when formatting.

set -euo pipefail

script_dir="${0:A:h}"
config_file="${script_dir}/.swiftformat"

swiftformat --config "${config_file}" "${@}"
