workspace(name = "simple_example")

local_repository(
    name = "cgrindel_rules_spm",
    path = "../..",
)

load(
    "@cgrindel_rules_spm//spm:deps.bzl",
    "spm_rules_dependencies",
)

spm_rules_dependencies()

load("@cgrindel_bazel_starlib//:deps.bzl", "bazel_starlib_dependencies")

bazel_starlib_dependencies()

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

load(
    "@build_bazel_rules_swift//swift:repositories.bzl",
    "swift_rules_dependencies",
)

swift_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:extras.bzl",
    "swift_rules_extra_dependencies",
)

swift_rules_extra_dependencies()

load("@cgrindel_rules_spm//spm:defs.bzl", "spm_pkg", "spm_repositories")

spm_repositories(
    name = "swift_pkgs",
    dependencies = [
        spm_pkg(
            "https://github.com/apple/swift-log.git",
            exact_version = "1.4.2",
            products = ["Logging"],
        ),
        spm_pkg(
            # Need to specify for the package because the URL basename does not
            # match the package name in the Package.swift.
            name = "libwebp",
            exact_version = "1.2.1",
            products = ["libwebp"],
            url = "https://github.com/SDWebImage/libwebp-Xcode.git",
        ),
        # GH147: Finish implementing support for Firebase
        # spm_pkg(
        #     # Need to specify for the package because the URL basename does not
        #     # match the package name in the Package.swift.
        #     name = "Firebase",
        #     exact_version = "9.5.0",
        #     products = ["FirebaseAnalytics"],
        #     url = "https://github.com/firebase/firebase-ios-sdk.git",
        # ),
    ],
)
