workspace(name = "package_with_deps_example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# MARK: - Apple and Swift Dependencies

http_archive(
    name = "build_bazel_rules_apple",
    sha256 = "0052d452af7742c8f3a4e0929763388a66403de363775db7e90adecb2ba4944b",
    url = "https://github.com/bazelbuild/rules_apple/releases/download/0.31.3/rules_apple.0.31.3.tar.gz",
)

load(
    "@build_bazel_rules_apple//apple:repositories.bzl",
    "apple_rules_dependencies",
)

apple_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:repositories.bzl",
    "swift_rules_dependencies",
)

swift_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:extras.bzl",
    "swift_rules_extra_dependencies",
)

swift_rules_extra_dependencies()

load(
    "@build_bazel_apple_support//lib:repositories.bzl",
    "apple_support_dependencies",
)

apple_support_dependencies()

# MARK: - rules_spm Dependencies

local_repository(
    name = "cgrindel_rules_spm",
    path = "../..",
)

load(
    "@cgrindel_rules_spm//spm:repositories.bzl",
    "rules_spm_dependencies",
)

rules_spm_dependencies()

# MARK: - External SPM Packages

load("@cgrindel_rules_spm//spm:spm.bzl", "spm_pkg", "spm_repositories")

spm_repositories(
    name = "swift_pkgs",
    dependencies = [
        spm_pkg(
            "https://github.com/vapor/vapor.git",
            name = "vapor",
            from_version = "4.0.0",
            products = ["Vapor"],
        ),
    ],
    platforms = [
        ".macOS(.v10_15)",
    ],
)

# MARK: - External Swift Code That Uses Bazel

http_archive(
    name = "cgrindel_swift_toolbox",
    sha256 = "3b1022dcb99f45753f94d9e6c2623bf4973c887bae52df8bb1b25ee46878bdff",
    strip_prefix = "swift_toolbox-0.2.0",
    url = "https://github.com/cgrindel/swift_toolbox/archive/v0.2.0.tar.gz",
)
