workspace(name = "vapor_example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# MARK: - rules_spm Dependencies

local_repository(
    name = "cgrindel_rules_spm",
    path = "../..",
)

load(
    "@cgrindel_rules_spm//spm:deps.bzl",
    "spm_rules_dependencies",
)

spm_rules_dependencies()

load("@cgrindel_bazel_starlib//:deps.bzl", "bazel_starlib_dependencies")

bazel_starlib_dependencies()

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

load(
    "@build_bazel_rules_swift//swift:repositories.bzl",
    "swift_rules_dependencies",
)

swift_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:extras.bzl",
    "swift_rules_extra_dependencies",
)

swift_rules_extra_dependencies()

# MARK: - External SPM Packages

load("@cgrindel_rules_spm//spm:defs.bzl", "spm_pkg", "spm_repositories")

spm_repositories(
    name = "swift_pkgs",
    dependencies = [
        spm_pkg(
            "https://github.com/vapor/vapor.git",
            exact_version = "4.54.1",
            products = [
                "Vapor",
                "XCTVapor",
            ],
        ),
        spm_pkg(
            "https://github.com/vapor/fluent.git",
            exact_version = "4.4.0",
            products = ["Fluent"],
        ),
        spm_pkg(
            "https://github.com/vapor/fluent-sqlite-driver.git",
            exact_version = "4.1.0",
            products = ["FluentSQLiteDriver"],
        ),
    ],
    # New concurrency stuff is supported in macOS v12.
    platforms = [
        ".macOS(.v12)",
    ],
    swift_version = "5.5",
)
