workspace(name = "rules_swift_package_manager_examples")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "build_bazel_rules_swift",
    sha256 = "f872c0388808c3f8de67e0c6d39b0beac4a65d7e07eff3ced123d0b102046fb6",
    url = "https://github.com/bazelbuild/rules_swift/releases/download/0.23.0/rules_swift.0.23.0.tar.gz",
)

load(
    "@build_bazel_rules_swift//swift:repositories.bzl",
    "swift_rules_dependencies",
)

swift_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:extras.bzl",
    "swift_rules_extra_dependencies",
)

swift_rules_extra_dependencies()

local_repository(
    name = "rules_swift_package_manager",
    path = "..",
)

load(
    "@rules_swift_package_manager//swift_package_manager:repositories.bzl",
    "rules_swift_package_manager_dependencies",
)

rules_swift_package_manager_dependencies()

load(
    "@rules_swift_package_manager//swift_package_manager:swift_package_manager.bzl",
    "spm_repository",
)

spm_repository(
    name = "apple_swift_log",
    sha256 = "de51662b35f47764b6e12e9f1d43e7de28f6dd64f05bc30a318cf978cf3bc473",
    strip_prefix = "swift-log-1.4.2",
    urls = ["https://github.com/apple/swift-log/archive/1.4.2.tar.gz"],
)
