workspace(name = "xcmetrics_example")

local_repository(
    name = "cgrindel_rules_spm",
    path = "../..",
)

load(
    "@cgrindel_rules_spm//spm:deps.bzl",
    "spm_rules_dependencies",
)

spm_rules_dependencies()

load("@cgrindel_bazel_starlib//:deps.bzl", "bazel_starlib_dependencies")

bazel_starlib_dependencies()

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

load(
    "@build_bazel_rules_swift//swift:repositories.bzl",
    "swift_rules_dependencies",
)

swift_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:extras.bzl",
    "swift_rules_extra_dependencies",
)

swift_rules_extra_dependencies()

load("@cgrindel_rules_spm//spm:defs.bzl", "spm_pkg", "spm_repositories")

# From GH189
spm_repositories(
    name = "xcode_metrics_packages",
    dependencies = [
        spm_pkg(
            "https://github.com/apple/swift-argument-parser",
            exact_version = "0.3.2",
            products = ["ArgumentParser"],
        ),
        spm_pkg(
            "https://github.com/spotify/XCMetrics",
            exact_version = "0.0.10",
            products = [
                "XCMetricsClient",
                "XCMetricsPlugins",
            ],
        ),
    ],
    platforms = [".macOS(.v10_15)"],
    swift_version = "5.5",
)
