name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  # macos_build:

  #   runs-on: macos-11.0

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Write local.bazelrc File
  #     shell: bash
  #     run: |
  #       cat >local.bazelrc <<EOF
  #       common --config=ci
  #       EOF

  #   - name: Output the Bazel Info
  #     shell: bash
  #     run: |
  #       bazelisk info

  #   - name: Execute Tests
  #     shell: bash
  #     run: |
  #       bazelisk test //... 

  #   - name: Build Anything Not Tested
  #     shell: bash
  #     run: |
  #       bazelisk build //... 

  #   - name: Test Simple Example
  #     shell: bash
  #     run: |
  #       cd examples/simple
  #       bazelisk test //...

  #   - name: Test Package With Shared Deps Example
  #     shell: bash
  #     run: |
  #       cd examples/package_with_shared_deps
  #       bazelisk test //...

  #   - name: Test Vapor Example
  #     shell: bash
  #     run: |
  #       cd examples/vapor
  #       bazelisk test //...

  #   - name: Test iOS Simulator Example
  #     shell: bash
  #     run: |
  #       cd examples/ios_sim
  #       bazelisk test //...

  ubuntu_build:

    runs-on: ubuntu-20.04

    env:
      CC: clang

    steps:
    - uses: actions/checkout@v2

    - name: Make sure that ld.gold is visible to clang
      shell: bash
      run: |
        set -x
        ld_gold_path=$(which ld.gold)
        # real_ld_gold_path=$(realpath "${ld_gold_path}")
        # clang_path=$(realpath $(which clang))
        # real_clang_path=$(realpath "${clang_path}")
        # real_clang_dir=$(dirname "${real_clang_path}")
        ld_path=$(which ld)
        ld_dir=$(dirname $ld_path)
        sudo mv "${ld_path}" "${ld_path}.HIDE"
        sudo cp "${ld_gold_path}" "${ld_path}"
        # realpath $(which ld)
        #
        # sudo ln -s "${real_ld_gold_path}" "${real_clang_dir}/ld.gold"
        # ls -la "${real_clang_dir}/ld.gold"
        #
        # echo "ld_gold_path: ${ld_gold_path}"
        # echo "clang_path: ${clang_path}"
        # echo "real_clang_path: ${real_clang_path}"
        # echo "real_clang_dir: ${real_clang_dir}"
        # exit 1
        # sudo find / -name "ld.gold"
        #
        # /usr/bin/ld.gold -plugin
        # ld_gold_path=$(realpath $(which ld.gold))
        # clang_path=$(realpath $(which clang))
        # clang_dir=$(dirname "${clang_path}")
        # # ls -la $(which clang)
        # # ls -la $(dirname $(which clang))
        # echo "ld_gold_path: ${ld_gold_path}"
        # echo "clang_path: ${clang_path}"
        # echo "clang_dir: ${clang_dir}"
        # sudo ln -s "${ld_gold_path}" "${clang_dir}"
        # echo "Direcotry ${clang_dir}"
        # ls -la "${clang_dir}"

    - name: Write local.bazelrc File
      shell: bash
      run: |
        cat >local.bazelrc <<EOF
        common --config=ci
        EOF

    - name: Output the Bazel Info
      shell: bash
      run: |
        bazelisk info

    - name: Execute Tests
      shell: bash
      run: |
        bazelisk test //... 

    - name: Build Anything Not Tested
      shell: bash
      run: |
        bazelisk build //... 

    - name: Test Simple Example
      shell: bash
      run: |
        cd examples/simple
        bazelisk test //... --verbose_failures --sandbox_debug

    - name: Test Package With Shared Deps Example
      shell: bash
      run: |
        cd examples/package_with_shared_deps
        bazelisk test //...

    - name: Test Vapor Example
      shell: bash
      run: |
        cd examples/vapor
        bazelisk test //...
