name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        type: string
      reset_tag:
        type: boolean
        default: false
  workflow_call:
    inputs:
      release_tag:
        required: true
        type: string
      reset_tag:
        type: boolean
        default: false

jobs:
  create_release:
    runs-on: ubuntu-latest
    env:
      CC: clang

    steps:
    - uses: actions/checkout@v3
    - uses: cgrindel/gha_set_up_bazel@v1
      with:
        repo_name: rules_spm
    - uses: tibdex/github-app-token@v1
      id: generate_token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - uses: cgrindel/gha_configure_git_user@v1
    - uses: cgrindel/gha_create_release@v1
      with:
        release_tag: ${{ github.event.inputs.release_tag }}
        reset_tag: ${{ github.event.inputs.reset_tag }}
        base_branch: ${{ github.event.inputs.base_branch }}
        github_token: ${{ steps.generate_token.outputs.token }}
